name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nodejsscan
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pytest
        pip install -r requirements.txt
  
    - name: Run tests
      run: |
        pytest -vv --cache-clear tests.py
      env:
        SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/nodejsscan
